# Generated by Django 3.2.3 on 2023-05-08 11:28

from django.db import migrations, models
import django.db.models.deletion
import friends.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('username',
                 models.CharField(
                    error_messages={
                        'unique': 'Пользователь с таким именем уже существует'
                    },
                    max_length=32,
                    unique=True,
                    validators=[friends.validators.username_validator],
                    verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('date_update',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='Дата обновления')),
                ('date_create',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата создания')),
                ('friends',
                 models.ManyToManyField(blank=True,
                                        related_name='friends',
                                        to='friends.User',
                                        verbose_name='Друзья')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='friends.user',
                                   verbose_name='Владелец профиля')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('status_req',
                 models.CharField(choices=[('', ''), ('', ''), ('', '')],
                                  max_length=24,
                                  verbose_name='')),
                ('date_update',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='Дата обновления')),
                ('date_sending',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата отправки')),
                ('recipient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='fr_recipient',
                                   to='friends.user',
                                   verbose_name='Имя получателя')),
                ('sender',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='fr_sender',
                                   to='friends.user',
                                   verbose_name='Имя отправителя')),
            ],
            options={
                'verbose_name': 'Заявка в друзья',
                'verbose_name_plural': 'Заявки в друзья',
                'ordering': ('sender',),
            },
        ),
        migrations.AddConstraint(
            model_name='friendshiprequest',
            constraint=models.UniqueConstraint(
                fields=('sender', 'recipient'),
                name='unique_sender_recipient'
            ),
        ),
    ]
