# Generated by Django 3.2.3 on 2023-05-08 13:56

from django.db import migrations, models
import friends.validators


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='date_sending',
            field=models.DateTimeField(auto_now_add=True, validators=[friends.validators.validate_of_date], verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='date_update',
            field=models.DateTimeField(auto_now=True, validators=[friends.validators.validate_of_date], verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status_req',
            field=models.CharField(choices=[('send', 'отправить'), ('accept', 'принять')], max_length=24, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, validators=[friends.validators.validate_of_date], verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_update',
            field=models.DateTimeField(auto_now=True, validators=[friends.validators.validate_of_date], verbose_name='Дата обновления'),
        ),
    ]
