# Generated by Django 3.2.3 on 2023-05-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20230508_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status_req',
            field=models.CharField(choices=[('send', 'отправить'), ('accept', 'принять'), ('friend', 'уже друзья')], max_length=24, verbose_name='Статус заявки'),
        ),
    ]
