# Generated by Django 3.2.3 on 2023-05-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friendshiprequest_status_req'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(
                fields=('user',),
                name='unique_user'
            ),
        ),
    ]
