# Generated by Django 3.2.3 on 2023-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_profile_unique_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status_req',
            field=models.CharField(
                choices=[('send', 'отправлен'),
                         ('incoming', 'получен'),
                         ('friend', 'уже друзья')],
                max_length=24,
                verbose_name='Статус заявки'),
        ),
    ]
